using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BB2Stats
{
    internal class Types
    {
        public enum ActionTypes {
            Move = 0,
            Block = 1,
            Blitz = 2,
            Pass = 3,
            HandOff = 4,
            Foul = 5,
            TakeDamage = 6,
            KickOff = 7,
            Ball = 8,
            Catch = 9,
            Touchdown = 10,
            FrontToBack = 11,
            WakeUp = 12,
            EventPitchInv = 13,
            PickUp = 14,
            Stupidity = 15,
            Land = 16,
            EatTeamMate = 17,
            Shadow = 18,
            Stab = 19,
            FrenzyStab = 20,
            Leap = 21,
            Chainsaw = 22,
            BallAndChain = 23,
            HailMaryPass = 24,
            PilingOn = 25,
            MultipleBlock = 26,
            HypnoticGaze = 27,
            KickOffReturn = 28,
            PassBlock = 29,
            HalflingChef = 30,
            FireballLaunch = 31,
            FireBallHit = 32,
            LightningBolt = 33,
            DeceiveReferee = 34,
            ScatterPlayer = 35,
            QuickSnap = 36,
            HighKick = 37,
            DumpOff = 38,
            DivingTackle = 39,
            ThrowTeamMate = 40,
            MultipleStab = 41,
            Activate = 42,
            PassBlockMoveLeap = 43,
            PassBlockLeapMove = 44,
            PassBlockLeap = 45,
            FansNumber = 46,
            InitialWeather = 47,
            SwelteringHeat = 48,
            Feed = 49,
            BombExplosionGenerator = 50,
            BombExplosionHit = 51,
            PassBomb = 52,
            CatchBomb = 53,
            ScatterBomb = 54,
            ForcedPassBomb = 55,
            HailMaryBomb = 56
        }

        public enum RollType
        {
            NoRoll = 0,
            GFI = 1,
            Dodge = 2,
            Armor = 3,
            Injury = 4,
            Block = 5,
            StandUp = 6,
            PickUp = 7,
            Casualty = 8,
            Catch = 9,
            Scatter = 10,
            ThrowIn = 11,
            Pass = 12,
            PushBack = 13,
            FollowUp = 14,
            DeceiveReferee = 15,
            Interception = 16,
            WakeUp = 17,
            PitchInv = 18,
            TouchBack = 19,
            BoneHead = 20,
            ReallyStupid = 21,
            WildAnimal = 22,
            Loner = 23,
            Land = 24,
            Regeneration = 25,
            ScatterPlayer = 26,
            Hungry = 27,
            EatTeamMate = 28,
            Dauntless = 29,
            SafeThrow = 30,
            JumpUp = 31,
            Shadowing = 32,
            DumpOff = 33,
            Stab = 34,
            FrenzyStab = 35,
            Leap = 36,
            FoulAppearance = 37,
            Tentacles = 38,
            Chainsaw = 39,
            TakeRoot = 40,
            BallAndChain = 41,
            HailMaryPass = 42,
            PilingOn = 43,
            DivingTackle = 44,
            Pro = 45,
            HypnoticGaze = 46,
            KickOffReturn = 47,
            PassBlock = 48,
            Animosity = 49,
            BloodLust = 50,
            Feed = 51,
            Bribe = 52,
            HalflingChef = 53,
            FireBallHit = 54,
            LightningBolt = 55,
            ThrowTeamMate = 56,
            AdditionalBlock = 57,
            WeatherScatter = 58,
            PilingOnArmor = 59,
            PilingOnInjury = 60,
            BlockWrestle = 61,
            BlockDodge = 62,
            BlockStandFirm = 63,
            BlockJuggernaut = 64,
            PushStandFirm = 65,
            Necromancer = 66,
            NurglesRot = 67,
            PushSideStep = 68,
            FansNumber = 69,
            InitialWeather = 70,
            SwelteringHeat = 71,
            BombHit = 72,
            ChainsawArmor = 73,
            HailMaryBomb = 74
        }

        public enum SubResultType
        {
            Accurate = 0,
            Scattered = 1,
            Fumbled = 2,
            Cancelled = 3
        }
    }
}
