//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 

namespace schemas.full_state
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Cell
    {

        private string yField;

        private string xField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Destination
    {

        private string yField;

        private string xField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Statistics
    {

        private string idCoachHomeField;

        private string shardedIdTeamListingAwayField;

        private string idCoachAwayField;

        private string shardedIdTeamListingHomeField;

        private string inflictedCasualtiesField;

        private string inflictedTacklesField;

        private string sustainedTacklesField;

        private string inflictedKOField;

        private string inflictedPushOutsField;

        private string inflictedInjuriesField;

        private string sustainedInjuriesField;

        private string sustainedCasualtiesField;

        private string sustainedKOField;

        private string inflictedMetersRunningField;

        private StatisticsDicesStat[] dicesStatField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdCoachHome
        {
            get
            {
                return this.idCoachHomeField;
            }
            set
            {
                this.idCoachHomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShardedIdTeamListingAway
        {
            get
            {
                return this.shardedIdTeamListingAwayField;
            }
            set
            {
                this.shardedIdTeamListingAwayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdCoachAway
        {
            get
            {
                return this.idCoachAwayField;
            }
            set
            {
                this.idCoachAwayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShardedIdTeamListingHome
        {
            get
            {
                return this.shardedIdTeamListingHomeField;
            }
            set
            {
                this.shardedIdTeamListingHomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InflictedCasualties
        {
            get
            {
                return this.inflictedCasualtiesField;
            }
            set
            {
                this.inflictedCasualtiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InflictedTackles
        {
            get
            {
                return this.inflictedTacklesField;
            }
            set
            {
                this.inflictedTacklesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SustainedTackles
        {
            get
            {
                return this.sustainedTacklesField;
            }
            set
            {
                this.sustainedTacklesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InflictedKO
        {
            get
            {
                return this.inflictedKOField;
            }
            set
            {
                this.inflictedKOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InflictedPushOuts
        {
            get
            {
                return this.inflictedPushOutsField;
            }
            set
            {
                this.inflictedPushOutsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InflictedInjuries
        {
            get
            {
                return this.inflictedInjuriesField;
            }
            set
            {
                this.inflictedInjuriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SustainedInjuries
        {
            get
            {
                return this.sustainedInjuriesField;
            }
            set
            {
                this.sustainedInjuriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SustainedCasualties
        {
            get
            {
                return this.sustainedCasualtiesField;
            }
            set
            {
                this.sustainedCasualtiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SustainedKO
        {
            get
            {
                return this.sustainedKOField;
            }
            set
            {
                this.sustainedKOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InflictedMetersRunning
        {
            get
            {
                return this.inflictedMetersRunningField;
            }
            set
            {
                this.inflictedMetersRunningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DicesStat", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StatisticsDicesStat[] DicesStat
        {
            get
            {
                return this.dicesStatField;
            }
            set
            {
                this.dicesStatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StatisticsDicesStat
    {

        private string blockDistribField;

        private string rollDistribField;

        private StatisticsDicesStatRollRowRollStatistics[][] rollField;

        private StatisticsDicesStatBlockRowBlockStatistics[][] blockField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BlockDistrib
        {
            get
            {
                return this.blockDistribField;
            }
            set
            {
                this.blockDistribField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RollDistrib
        {
            get
            {
                return this.rollDistribField;
            }
            set
            {
                this.rollDistribField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RowRollStatistics", typeof(StatisticsDicesStatRollRowRollStatistics[]), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public StatisticsDicesStatRollRowRollStatistics[][] Roll
        {
            get
            {
                return this.rollField;
            }
            set
            {
                this.rollField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RowBlockStatistics", typeof(StatisticsDicesStatBlockRowBlockStatistics[]), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public StatisticsDicesStatBlockRowBlockStatistics[][] Block
        {
            get
            {
                return this.blockField;
            }
            set
            {
                this.blockField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StatisticsDicesStatRollRowRollStatistics
    {

        private string rollTypeField;

        private string successField;

        private string failureField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RollType
        {
            get
            {
                return this.rollTypeField;
            }
            set
            {
                this.rollTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Failure
        {
            get
            {
                return this.failureField;
            }
            set
            {
                this.failureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StatisticsDicesStatBlockRowBlockStatistics
    {

        private string attackerField;

        private string choiceField;

        private string dicesField;

        private string redField;

        private string defenderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attacker
        {
            get
            {
                return this.attackerField;
            }
            set
            {
                this.attackerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Choice
        {
            get
            {
                return this.choiceField;
            }
            set
            {
                this.choiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dices
        {
            get
            {
                return this.dicesField;
            }
            set
            {
                this.dicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Red
        {
            get
            {
                return this.redField;
            }
            set
            {
                this.redField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Defender
        {
            get
            {
                return this.defenderField;
            }
            set
            {
                this.defenderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Data
    {

        private string lobbyIdField;

        private string maField;

        private string nameField;

        private string agField;

        private string levelField;

        private string numberField;

        private string experienceField;

        private string idHeadField;

        private string listCasualtiesField;

        private string teamIdField;

        private string contractField;

        private string valueField;

        private string avField;

        private string stField;

        private string listSkillsField;

        private string idField;

        private string idPlayerTypesField;

        private string treasuryBeforeInducementsField;

        private string popularityField;

        private string idCheerleadersRaceField;

        private string idRaceField;

        private string treasuryField;

        private string rerollField;

        private string logoField;

        private string coachSlotField;

        private string teamColorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LobbyId
        {
            get
            {
                return this.lobbyIdField;
            }
            set
            {
                this.lobbyIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ma
        {
            get
            {
                return this.maField;
            }
            set
            {
                this.maField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ag
        {
            get
            {
                return this.agField;
            }
            set
            {
                this.agField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Experience
        {
            get
            {
                return this.experienceField;
            }
            set
            {
                this.experienceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdHead
        {
            get
            {
                return this.idHeadField;
            }
            set
            {
                this.idHeadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ListCasualties
        {
            get
            {
                return this.listCasualtiesField;
            }
            set
            {
                this.listCasualtiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TeamId
        {
            get
            {
                return this.teamIdField;
            }
            set
            {
                this.teamIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Contract
        {
            get
            {
                return this.contractField;
            }
            set
            {
                this.contractField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Av
        {
            get
            {
                return this.avField;
            }
            set
            {
                this.avField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string St
        {
            get
            {
                return this.stField;
            }
            set
            {
                this.stField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ListSkills
        {
            get
            {
                return this.listSkillsField;
            }
            set
            {
                this.listSkillsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdPlayerTypes
        {
            get
            {
                return this.idPlayerTypesField;
            }
            set
            {
                this.idPlayerTypesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TreasuryBeforeInducements
        {
            get
            {
                return this.treasuryBeforeInducementsField;
            }
            set
            {
                this.treasuryBeforeInducementsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Popularity
        {
            get
            {
                return this.popularityField;
            }
            set
            {
                this.popularityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdCheerleadersRace
        {
            get
            {
                return this.idCheerleadersRaceField;
            }
            set
            {
                this.idCheerleadersRaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdRace
        {
            get
            {
                return this.idRaceField;
            }
            set
            {
                this.idRaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Treasury
        {
            get
            {
                return this.treasuryField;
            }
            set
            {
                this.treasuryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reroll
        {
            get
            {
                return this.rerollField;
            }
            set
            {
                this.rerollField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Logo
        {
            get
            {
                return this.logoField;
            }
            set
            {
                this.logoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CoachSlot
        {
            get
            {
                return this.coachSlotField;
            }
            set
            {
                this.coachSlotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TeamColor
        {
            get
            {
                return this.teamColorField;
            }
            set
            {
                this.teamColorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Id
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class RulesEventFullState
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoardState", typeof(RulesEventFullStateBoardState), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Cell", typeof(Cell))]
        [System.Xml.Serialization.XmlElementAttribute("Data", typeof(Data))]
        [System.Xml.Serialization.XmlElementAttribute("Destination", typeof(Destination))]
        [System.Xml.Serialization.XmlElementAttribute("GameInfos", typeof(RulesEventFullStateGameInfos), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Id", typeof(Id))]
        [System.Xml.Serialization.XmlElementAttribute("Messages", typeof(RulesEventFullStateMessages), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("ReplayInfos", typeof(RulesEventFullStateReplayInfos), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Statistics", typeof(Statistics))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateBoardState
    {

        private string currentPhaseField;

        private RulesEventFullStateBoardStateCampaignSpecifics[] campaignSpecificsField;

        private RulesEventFullStateBoardStateBall[] ballField;

        private RulesEventFullStateBoardStateBomb[] bombField;

        private Statistics[] statisticsField;

        private RulesEventFullStateBoardStateTeamState[] listTeamsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrentPhase
        {
            get
            {
                return this.currentPhaseField;
            }
            set
            {
                this.currentPhaseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CampaignSpecifics", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RulesEventFullStateBoardStateCampaignSpecifics[] CampaignSpecifics
        {
            get
            {
                return this.campaignSpecificsField;
            }
            set
            {
                this.campaignSpecificsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ball", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RulesEventFullStateBoardStateBall[] Ball
        {
            get
            {
                return this.ballField;
            }
            set
            {
                this.ballField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bomb", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RulesEventFullStateBoardStateBomb[] Bomb
        {
            get
            {
                return this.bombField;
            }
            set
            {
                this.bombField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Statistics")]
        public Statistics[] Statistics
        {
            get
            {
                return this.statisticsField;
            }
            set
            {
                this.statisticsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TeamState", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public RulesEventFullStateBoardStateTeamState[] ListTeams
        {
            get
            {
                return this.listTeamsField;
            }
            set
            {
                this.listTeamsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateBoardStateCampaignSpecifics
    {

        private string listDangerousCellsField;

        private string listPoisonnedPlayersField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ListDangerousCells
        {
            get
            {
                return this.listDangerousCellsField;
            }
            set
            {
                this.listDangerousCellsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ListPoisonnedPlayers
        {
            get
            {
                return this.listPoisonnedPlayersField;
            }
            set
            {
                this.listPoisonnedPlayersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateBoardStateBall
    {

        private string isHeldField;

        private Cell[] cellField;

        private Destination[] destinationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsHeld
        {
            get
            {
                return this.isHeldField;
            }
            set
            {
                this.isHeldField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cell")]
        public Cell[] Cell
        {
            get
            {
                return this.cellField;
            }
            set
            {
                this.cellField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Destination")]
        public Destination[] Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateBoardStateBomb
    {

        private Cell[] cellField;

        private Destination[] destinationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cell")]
        public Cell[] Cell
        {
            get
            {
                return this.cellField;
            }
            set
            {
                this.cellField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Destination")]
        public Destination[] Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateBoardStateTeamState
    {

        private string kickOffTurnField;

        private string handOfferIdField;

        private string foulAvailableField;

        private string passerIdField;

        private string blitzerIdField;

        private string gameTurnField;

        private string fameField;

        private string wizardEndsTurnField;

        private string inducementsTurnField;

        private string listInducementsField;

        private string teamRerollAvailableField;

        private string rerollNumberField;

        private string listMercenariesField;

        private string nbSupportersField;

        private string sideField;

        private string apothecaryAvailableField;

        private RulesEventFullStateBoardStateTeamStatePlayerState[] listPitchPlayersField;

        private Data[] dataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KickOffTurn
        {
            get
            {
                return this.kickOffTurnField;
            }
            set
            {
                this.kickOffTurnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HandOfferId
        {
            get
            {
                return this.handOfferIdField;
            }
            set
            {
                this.handOfferIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FoulAvailable
        {
            get
            {
                return this.foulAvailableField;
            }
            set
            {
                this.foulAvailableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PasserId
        {
            get
            {
                return this.passerIdField;
            }
            set
            {
                this.passerIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BlitzerId
        {
            get
            {
                return this.blitzerIdField;
            }
            set
            {
                this.blitzerIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameTurn
        {
            get
            {
                return this.gameTurnField;
            }
            set
            {
                this.gameTurnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fame
        {
            get
            {
                return this.fameField;
            }
            set
            {
                this.fameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WizardEndsTurn
        {
            get
            {
                return this.wizardEndsTurnField;
            }
            set
            {
                this.wizardEndsTurnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InducementsTurn
        {
            get
            {
                return this.inducementsTurnField;
            }
            set
            {
                this.inducementsTurnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ListInducements
        {
            get
            {
                return this.listInducementsField;
            }
            set
            {
                this.listInducementsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TeamRerollAvailable
        {
            get
            {
                return this.teamRerollAvailableField;
            }
            set
            {
                this.teamRerollAvailableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RerollNumber
        {
            get
            {
                return this.rerollNumberField;
            }
            set
            {
                this.rerollNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ListMercenaries
        {
            get
            {
                return this.listMercenariesField;
            }
            set
            {
                this.listMercenariesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NbSupporters
        {
            get
            {
                return this.nbSupportersField;
            }
            set
            {
                this.nbSupportersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Side
        {
            get
            {
                return this.sideField;
            }
            set
            {
                this.sideField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApothecaryAvailable
        {
            get
            {
                return this.apothecaryAvailableField;
            }
            set
            {
                this.apothecaryAvailableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PlayerState", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public RulesEventFullStateBoardStateTeamStatePlayerState[] ListPitchPlayers
        {
            get
            {
                return this.listPitchPlayersField;
            }
            set
            {
                this.listPitchPlayersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Data")]
        public Data[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateBoardStateTeamStatePlayerState
    {

        private string canDeclareBlitzField;

        private string gfiField;

        private string idField;

        private string canBlockField;

        private string canActField;

        private string canHandOffField;

        private string tackleZoneField;

        private string statusField;

        private string movePointField;

        private string canPassField;

        private string situationField;

        private string listCasualtiesField;

        private string experienceGainedField;

        private Cell cellField;

        private Statistics statisticsField;

        private Data[] dataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanDeclareBlitz
        {
            get
            {
                return this.canDeclareBlitzField;
            }
            set
            {
                this.canDeclareBlitzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Gfi
        {
            get
            {
                return this.gfiField;
            }
            set
            {
                this.gfiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanBlock
        {
            get
            {
                return this.canBlockField;
            }
            set
            {
                this.canBlockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanAct
        {
            get
            {
                return this.canActField;
            }
            set
            {
                this.canActField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanHandOff
        {
            get
            {
                return this.canHandOffField;
            }
            set
            {
                this.canHandOffField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TackleZone
        {
            get
            {
                return this.tackleZoneField;
            }
            set
            {
                this.tackleZoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MovePoint
        {
            get
            {
                return this.movePointField;
            }
            set
            {
                this.movePointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanPass
        {
            get
            {
                return this.canPassField;
            }
            set
            {
                this.canPassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Situation
        {
            get
            {
                return this.situationField;
            }
            set
            {
                this.situationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ListCasualties
        {
            get
            {
                return this.listCasualtiesField;
            }
            set
            {
                this.listCasualtiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExperienceGained
        {
            get
            {
                return this.experienceGainedField;
            }
            set
            {
                this.experienceGainedField = value;
            }
        }

        /// <remarks/>
        public Cell Cell
        {
            get
            {
                return this.cellField;
            }
            set
            {
                this.cellField = value;
            }
        }

        /// <remarks/>
        public Statistics Statistics
        {
            get
            {
                return this.statisticsField;
            }
            set
            {
                this.statisticsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Data")]
        public Data[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateGameInfos
    {

        private string answerClockField;

        private string serverReconnectionAllowedTimeField;

        private string clientDelayDetectionPingIntervallField;

        private string turnClockDurationField;

        private string teamStadiumOwnerField;

        private string idField;

        private string levelCabalVisionField;

        private string clockField;

        private string structStadiumField;

        private string localCoachSlotField;

        private string stateField;

        private string stadiumField;

        private string ballTypeField;

        private string turnClockField;

        private string mapField;

        private string playingCoachSlotField;

        private string serverDelayDetectionThresholdField;

        private string clientReconnectionIntervallField;

        private string maxPausePerCoachField;

        private string nameStadiumField;

        private string levelStadiumField;

        private string modeField;

        private string isPausedField;

        private RulesEventFullStateGameInfosCoachesInfosCoachInfos[][] coachesInfosField;

        private RulesEventFullStateGameInfosRowLeague[] rowLeagueField;

        private RulesEventFullStateGameInfosRowCompetition[] rowCompetitionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnswerClock
        {
            get
            {
                return this.answerClockField;
            }
            set
            {
                this.answerClockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServerReconnectionAllowedTime
        {
            get
            {
                return this.serverReconnectionAllowedTimeField;
            }
            set
            {
                this.serverReconnectionAllowedTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientDelayDetectionPingIntervall
        {
            get
            {
                return this.clientDelayDetectionPingIntervallField;
            }
            set
            {
                this.clientDelayDetectionPingIntervallField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TurnClockDuration
        {
            get
            {
                return this.turnClockDurationField;
            }
            set
            {
                this.turnClockDurationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TeamStadiumOwner
        {
            get
            {
                return this.teamStadiumOwnerField;
            }
            set
            {
                this.teamStadiumOwnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LevelCabalVision
        {
            get
            {
                return this.levelCabalVisionField;
            }
            set
            {
                this.levelCabalVisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Clock
        {
            get
            {
                return this.clockField;
            }
            set
            {
                this.clockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StructStadium
        {
            get
            {
                return this.structStadiumField;
            }
            set
            {
                this.structStadiumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocalCoachSlot
        {
            get
            {
                return this.localCoachSlotField;
            }
            set
            {
                this.localCoachSlotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Stadium
        {
            get
            {
                return this.stadiumField;
            }
            set
            {
                this.stadiumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BallType
        {
            get
            {
                return this.ballTypeField;
            }
            set
            {
                this.ballTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TurnClock
        {
            get
            {
                return this.turnClockField;
            }
            set
            {
                this.turnClockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Map
        {
            get
            {
                return this.mapField;
            }
            set
            {
                this.mapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlayingCoachSlot
        {
            get
            {
                return this.playingCoachSlotField;
            }
            set
            {
                this.playingCoachSlotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServerDelayDetectionThreshold
        {
            get
            {
                return this.serverDelayDetectionThresholdField;
            }
            set
            {
                this.serverDelayDetectionThresholdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientReconnectionIntervall
        {
            get
            {
                return this.clientReconnectionIntervallField;
            }
            set
            {
                this.clientReconnectionIntervallField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaxPausePerCoach
        {
            get
            {
                return this.maxPausePerCoachField;
            }
            set
            {
                this.maxPausePerCoachField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NameStadium
        {
            get
            {
                return this.nameStadiumField;
            }
            set
            {
                this.nameStadiumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LevelStadium
        {
            get
            {
                return this.levelStadiumField;
            }
            set
            {
                this.levelStadiumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mode
        {
            get
            {
                return this.modeField;
            }
            set
            {
                this.modeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsPaused
        {
            get
            {
                return this.isPausedField;
            }
            set
            {
                this.isPausedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CoachInfos", typeof(RulesEventFullStateGameInfosCoachesInfosCoachInfos[]), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public RulesEventFullStateGameInfosCoachesInfosCoachInfos[][] CoachesInfos
        {
            get
            {
                return this.coachesInfosField;
            }
            set
            {
                this.coachesInfosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RowLeague", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RulesEventFullStateGameInfosRowLeague[] RowLeague
        {
            get
            {
                return this.rowLeagueField;
            }
            set
            {
                this.rowLeagueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RowCompetition", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RulesEventFullStateGameInfosRowCompetition[] RowCompetition
        {
            get
            {
                return this.rowCompetitionField;
            }
            set
            {
                this.rowCompetitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateGameInfosCoachesInfosCoachInfos
    {

        private string slotField;

        private string pauseUsedField;

        private string loginField;

        private string userIdField;

        private string ownedDLCField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Slot
        {
            get
            {
                return this.slotField;
            }
            set
            {
                this.slotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PauseUsed
        {
            get
            {
                return this.pauseUsedField;
            }
            set
            {
                this.pauseUsedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OwnedDLC
        {
            get
            {
                return this.ownedDLCField;
            }
            set
            {
                this.ownedDLCField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateGameInfosRowLeague
    {

        private string emailContactsField;

        private string editionField;

        private string idOwnerField;

        private string leagueTypeField;

        private string logoField;

        private string marketPlaceLastRookieProcessField;

        private string marketPlaceRookieGeneratedField;

        private string hasPasswordField;

        private string soloField;

        private string descriptionField;

        private string marketPlaceField;

        private string needValidationField;

        private string phaseField;

        private string passwordField;

        private string dataField;

        private string dateLastMatchField;

        private string nameField;

        private string createdField;

        private string officialField;

        private string websitesField;

        private string treasurySpField;

        private string nbRegisteredTeamsField;

        private string flagsField;

        private Id[] idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EmailContacts
        {
            get
            {
                return this.emailContactsField;
            }
            set
            {
                this.emailContactsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Edition
        {
            get
            {
                return this.editionField;
            }
            set
            {
                this.editionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdOwner
        {
            get
            {
                return this.idOwnerField;
            }
            set
            {
                this.idOwnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LeagueType
        {
            get
            {
                return this.leagueTypeField;
            }
            set
            {
                this.leagueTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Logo
        {
            get
            {
                return this.logoField;
            }
            set
            {
                this.logoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MarketPlaceLastRookieProcess
        {
            get
            {
                return this.marketPlaceLastRookieProcessField;
            }
            set
            {
                this.marketPlaceLastRookieProcessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MarketPlaceRookieGenerated
        {
            get
            {
                return this.marketPlaceRookieGeneratedField;
            }
            set
            {
                this.marketPlaceRookieGeneratedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HasPassword
        {
            get
            {
                return this.hasPasswordField;
            }
            set
            {
                this.hasPasswordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Solo
        {
            get
            {
                return this.soloField;
            }
            set
            {
                this.soloField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MarketPlace
        {
            get
            {
                return this.marketPlaceField;
            }
            set
            {
                this.marketPlaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NeedValidation
        {
            get
            {
                return this.needValidationField;
            }
            set
            {
                this.needValidationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Phase
        {
            get
            {
                return this.phaseField;
            }
            set
            {
                this.phaseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateLastMatch
        {
            get
            {
                return this.dateLastMatchField;
            }
            set
            {
                this.dateLastMatchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Official
        {
            get
            {
                return this.officialField;
            }
            set
            {
                this.officialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Websites
        {
            get
            {
                return this.websitesField;
            }
            set
            {
                this.websitesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TreasurySp
        {
            get
            {
                return this.treasurySpField;
            }
            set
            {
                this.treasurySpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NbRegisteredTeams
        {
            get
            {
                return this.nbRegisteredTeamsField;
            }
            set
            {
                this.nbRegisteredTeamsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Flags
        {
            get
            {
                return this.flagsField;
            }
            set
            {
                this.flagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Id")]
        public Id[] Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateGameInfosRowCompetition
    {

        private string idOwnerField;

        private string rankedChallengeAllowedField;

        private string logoField;

        private string rankedMatchAllowedField;

        private string checkinPriceField;

        private string automatchAllowedField;

        private string keepReplayPolicyField;

        private string cloneOnNextLeagueEditionField;

        private string leaguePhaseField;

        private string challengeAllowedField;

        private string prematchEventsField;

        private string flagsField;

        private string idCompetitionTypesField;

        private string registrationModeField;

        private string nbRoundsField;

        private string nbTeamsMaxField;

        private string competitionStatusField;

        private string needValidationField;

        private string unRankedChallengeAllowedField;

        private string currentRoundField;

        private string nameField;

        private string leagueEditionField;

        private string unRankedMatchAllowedField;

        private string pureAutomatchField;

        private string concedeLimitField;

        private string nbRegisteredTeamsField;

        private string acceptTicketRequestField;

        private string turnDurationField;

        private string gameOptionsField;

        private RulesEventFullStateGameInfosRowCompetitionIdPreviousEdition[] idPreviousEditionField;

        private Id[] idField;

        private RulesEventFullStateGameInfosRowCompetitionIdLeague[] idLeagueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdOwner
        {
            get
            {
                return this.idOwnerField;
            }
            set
            {
                this.idOwnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RankedChallengeAllowed
        {
            get
            {
                return this.rankedChallengeAllowedField;
            }
            set
            {
                this.rankedChallengeAllowedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Logo
        {
            get
            {
                return this.logoField;
            }
            set
            {
                this.logoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RankedMatchAllowed
        {
            get
            {
                return this.rankedMatchAllowedField;
            }
            set
            {
                this.rankedMatchAllowedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckinPrice
        {
            get
            {
                return this.checkinPriceField;
            }
            set
            {
                this.checkinPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AutomatchAllowed
        {
            get
            {
                return this.automatchAllowedField;
            }
            set
            {
                this.automatchAllowedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KeepReplayPolicy
        {
            get
            {
                return this.keepReplayPolicyField;
            }
            set
            {
                this.keepReplayPolicyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CloneOnNextLeagueEdition
        {
            get
            {
                return this.cloneOnNextLeagueEditionField;
            }
            set
            {
                this.cloneOnNextLeagueEditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LeaguePhase
        {
            get
            {
                return this.leaguePhaseField;
            }
            set
            {
                this.leaguePhaseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ChallengeAllowed
        {
            get
            {
                return this.challengeAllowedField;
            }
            set
            {
                this.challengeAllowedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrematchEvents
        {
            get
            {
                return this.prematchEventsField;
            }
            set
            {
                this.prematchEventsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Flags
        {
            get
            {
                return this.flagsField;
            }
            set
            {
                this.flagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdCompetitionTypes
        {
            get
            {
                return this.idCompetitionTypesField;
            }
            set
            {
                this.idCompetitionTypesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RegistrationMode
        {
            get
            {
                return this.registrationModeField;
            }
            set
            {
                this.registrationModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NbRounds
        {
            get
            {
                return this.nbRoundsField;
            }
            set
            {
                this.nbRoundsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NbTeamsMax
        {
            get
            {
                return this.nbTeamsMaxField;
            }
            set
            {
                this.nbTeamsMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompetitionStatus
        {
            get
            {
                return this.competitionStatusField;
            }
            set
            {
                this.competitionStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NeedValidation
        {
            get
            {
                return this.needValidationField;
            }
            set
            {
                this.needValidationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnRankedChallengeAllowed
        {
            get
            {
                return this.unRankedChallengeAllowedField;
            }
            set
            {
                this.unRankedChallengeAllowedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrentRound
        {
            get
            {
                return this.currentRoundField;
            }
            set
            {
                this.currentRoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LeagueEdition
        {
            get
            {
                return this.leagueEditionField;
            }
            set
            {
                this.leagueEditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnRankedMatchAllowed
        {
            get
            {
                return this.unRankedMatchAllowedField;
            }
            set
            {
                this.unRankedMatchAllowedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PureAutomatch
        {
            get
            {
                return this.pureAutomatchField;
            }
            set
            {
                this.pureAutomatchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ConcedeLimit
        {
            get
            {
                return this.concedeLimitField;
            }
            set
            {
                this.concedeLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NbRegisteredTeams
        {
            get
            {
                return this.nbRegisteredTeamsField;
            }
            set
            {
                this.nbRegisteredTeamsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AcceptTicketRequest
        {
            get
            {
                return this.acceptTicketRequestField;
            }
            set
            {
                this.acceptTicketRequestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TurnDuration
        {
            get
            {
                return this.turnDurationField;
            }
            set
            {
                this.turnDurationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameOptions
        {
            get
            {
                return this.gameOptionsField;
            }
            set
            {
                this.gameOptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IdPreviousEdition", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RulesEventFullStateGameInfosRowCompetitionIdPreviousEdition[] IdPreviousEdition
        {
            get
            {
                return this.idPreviousEditionField;
            }
            set
            {
                this.idPreviousEditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Id")]
        public Id[] Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IdLeague", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RulesEventFullStateGameInfosRowCompetitionIdLeague[] IdLeague
        {
            get
            {
                return this.idLeagueField;
            }
            set
            {
                this.idLeagueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateGameInfosRowCompetitionIdPreviousEdition
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateGameInfosRowCompetitionIdLeague
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateMessages
    {

        private RulesEventFullStateMessagesStringMessage[] stringMessageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StringMessage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RulesEventFullStateMessagesStringMessage[] StringMessage
        {
            get
            {
                return this.stringMessageField;
            }
            set
            {
                this.stringMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateMessagesStringMessage
    {

        private string nameField;

        private string messageDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MessageData
        {
            get
            {
                return this.messageDataField;
            }
            set
            {
                this.messageDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RulesEventFullStateReplayInfos
    {

        private string isLiveField;

        private string currentPositionField;

        private string nbPositionsField;

        private string isReplayField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsLive
        {
            get
            {
                return this.isLiveField;
            }
            set
            {
                this.isLiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrentPosition
        {
            get
            {
                return this.currentPositionField;
            }
            set
            {
                this.currentPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NbPositions
        {
            get
            {
                return this.nbPositionsField;
            }
            set
            {
                this.nbPositionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsReplay
        {
            get
            {
                return this.isReplayField;
            }
            set
            {
                this.isReplayField = value;
            }
        }
    }
}