//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace BB2Stats.schemas.end_turn
{
    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class RulesEventEndTurn
    {

        private string turnClockField;

        private string jumpHalfTimeField;

        private string playingTeamField;

        private string nextTurnTypeField;

        private string touchdownScorerField;

        private string jumpAheadField;

        private string listTeamInfosField;

        private string newDriveField;

        private string turnoverField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TurnClock
        {
            get
            {
                return this.turnClockField;
            }
            set
            {
                this.turnClockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JumpHalfTime
        {
            get
            {
                return this.jumpHalfTimeField;
            }
            set
            {
                this.jumpHalfTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlayingTeam
        {
            get
            {
                return this.playingTeamField;
            }
            set
            {
                this.playingTeamField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NextTurnType
        {
            get
            {
                return this.nextTurnTypeField;
            }
            set
            {
                this.nextTurnTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TouchdownScorer
        {
            get
            {
                return this.touchdownScorerField;
            }
            set
            {
                this.touchdownScorerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JumpAhead
        {
            get
            {
                return this.jumpAheadField;
            }
            set
            {
                this.jumpAheadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ListTeamInfos
        {
            get
            {
                return this.listTeamInfosField;
            }
            set
            {
                this.listTeamInfosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NewDrive
        {
            get
            {
                return this.newDriveField;
            }
            set
            {
                this.newDriveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Turnover
        {
            get
            {
                return this.turnoverField;
            }
            set
            {
                this.turnoverField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private RulesEventEndTurn[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RulesEventEndTurn")]
        public RulesEventEndTurn[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

}